import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/Components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#8B35B8",
          dark: "#5C1F82",
          light: "#E9D5FF",
          glow: "#8B35B820",
          50: "#F5EEFA",
          100: "#F3E8FF",
          200: "#E9D5FF",
          300: "#D4B8EB",
          400: "#9B5DC7",
          500: "#8B35B8",
          600: "#7A2FA3",
          700: "#5C1F82",
          800: "#4A1970",
          900: "#381355",
        },
        secondary: "#5C1F82",
        charcoal: "#3D3C3C",
        accent: {
          DEFAULT: "#D4A847",
          gold: "#D4A847",
          light: "#E8C56A",
          dark: "#B88A2E",
        },
        "accent-saffron": "#F4821A",
        "warm-accent": "#F4821A",
        brand: {
          bg: "#FAF9FF",
          surface: "#FFFFFF",
          purple: "#8B35B8",
          "purple-deep": "#5C1F82",
          gold: "#D4A847",
          "gold-light": "#E8C56A",
          cream: "#FAF9FF",
          "cream-dark": "#F3E8FF",
        },
        "text-primary": "#1A1A1A",
        "text-secondary": "#6B7280",
        "text-muted": "#9CA3AF",
        "border-purple": "#D8B4FE",
        neutral: {
          50: "#FAFAFA",
          100: "#F5F5F5",
          200: "#E5E5E5",
          300: "#D4D4D4",
          400: "#A3A3A3",
          500: "#737373",
          600: "#6B7280",
          700: "#4B5563",
          800: "#374151",
          900: "#1A1A1A",
        },
        success: "#16A34A",
        error: "#DC2626",
        warning: "#F59E0B",
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
      fontFamily: {
        heading: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        body: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        serif: ["Georgia", "serif"],
      },
      borderRadius: {
        "4xl": "2rem",
        "5xl": "2.5rem",
      },
      boxShadow: {
        card: "0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)",
        "card-hover": "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.04)",
        glass: "0 8px 32px rgba(0, 0, 0, 0.08)",
        "glass-hover": "0 16px 48px rgba(0, 0, 0, 0.12)",
        premium: "0 20px 60px rgba(0, 0, 0, 0.1)",
        gold: "0 4px 20px rgba(0, 0, 0, 0.1)", // Neutralized
        "inner-subtle": "inset 0 1px 3px rgba(0,0,0,0.06)",
      },
      backgroundImage: {
        "brand-gradient": "linear-gradient(135deg, #8B35B8 0%, #5C1F82 50%, #8B35B8 100%)",
        "gold-gradient": "linear-gradient(90deg, #D4A847, #F0C060)",
        "cream-gradient": "linear-gradient(180deg, #FFFFFF 0%, #FAF9FF 100%)",
        "hero-gradient": "linear-gradient(135deg, rgba(139,53,184,0.92) 0%, rgba(92,31,130,0.9) 100%)",
        "hero-dark": "linear-gradient(135deg, #3D3C3C 0%, #1A1A1A 100%)",
        "section-purple": "linear-gradient(135deg, #8B35B8 0%, #5C1F82 100%)",
        "section-light-purple": "linear-gradient(180deg, #FAF9FF 0%, #F3E8FF 100%)",
        shimmer: "linear-gradient(90deg, #F5EEFA 25%, #EADCF5 50%, #F5EEFA 75%)",
        "shimmer-green": "linear-gradient(90deg, #f0fdf4 25%, #dcfce7 50%, #f0fdf4 75%)",
      },
      animation: {
        shimmer: "shimmer 1.5s infinite",
        "fade-in": "fadeIn 0.6s ease-out forwards",
        "fade-in-up": "fadeInUp 0.5s ease-out forwards",
        "fade-in-down": "fadeInDown 0.4s ease-out forwards",
        "slide-in-right": "slideInRight 0.4s ease-out forwards",
        "slide-in-left": "slideInLeft 0.4s ease-out forwards",
        "scale-in": "scaleIn 0.3s ease-out forwards",
        "bounce-subtle": "bounceSubtle 0.6s ease-out forwards",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        "spin-slow": "spin 3s linear infinite",
        float: "float 3s ease-in-out infinite",
        "draw-underline": "drawUnderline 0.6s ease-out forwards",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeInDown: {
          "0%": { opacity: "0", transform: "translateY(-16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(24px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-24px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.92)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        bounceSubtle: {
          "0%": { transform: "scale(1)" },
          "30%": { transform: "scale(1.15)" },
          "60%": { transform: "scale(0.95)" },
          "100%": { transform: "scale(1)" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(212, 160, 23, 0.4)" },
          "50%": { boxShadow: "0 0 0 8px rgba(212, 160, 23, 0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        drawUnderline: {
          "0%": { width: "0%" },
          "100%": { width: "100%" },
        },
      },
      transitionTimingFunction: {
        "bounce-out": "cubic-bezier(0.34, 1.56, 0.64, 1)",
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      spacing: {
        "safe-bottom": "env(safe-area-inset-bottom)",
        "safe-top": "env(safe-area-inset-top)",
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
} satisfies Config;
